# ---------------------------
# Backend Deployment
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD

            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"


          resources:
            requests:
              cpu: {{ .Values.resources.backend.requests.cpu | default "100m" }}
              memory: {{ .Values.resources.backend.requests.memory | default "256Mi" }}
            limits:
              cpu: {{ .Values.resources.backend.limits.cpu | default "500m" }}
              memory: {{ .Values.resources.backend.limits.memory | default "512Mi" }}

---

# ---------------------------
# Frontend Deployment
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.service.frontend.port }}
          env:
            - name: API_URL
              value: "http://{{ .Values.ingress.host }}/api"

          resources:
            requests:
              cpu: {{ .Values.resources.frontend.requests.cpu | default "50m" }}
              memory: {{ .Values.resources.frontend.requests.memory | default "128Mi" }}
            limits:
              cpu: {{ .Values.resources.frontend.limits.cpu | default "250m" }}
              memory: {{ .Values.resources.frontend.limits.memory | default "256Mi" }}
