replicaCount: 3

image:
  backend:
    tag: "1.0.0"
  frontend:
    tag: "1.0.0"

ingress:
  host: pedido.com

resources:
  backend:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  frontend:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
